version: "3.8"
services:
  test-node: 
    build: ./test-node
    container_name: ryanapi
    ports: 
      - '4000:8081'
    volumes:
      - ./test-node:/app
      - ./test-node/node_modules:/app/node_modules
  myblog:
    build: ./myblog
    container_name: ryanblog
    ports:
      - '3000:3000'
    #volumes:
    #  - ./myblog:/app
    #  - ./myblog/node_modules:/app/node_modules
    # adding stdin_open and tty starts the container in interactive mode
    stdin_open: true
    tty: true